#!/bin/bash

brew install getantibody/tap/antibody tree nnn zsh highlight fzf the_platinum_searcher peco lnav coreutils
brew cask install xquartz
mv -v ~/.zshrc ~/.zshrc.pre-artisan 2> /dev/null
ln -sf ~/.artisan/zsh/zshrc ~/.zshrc
mv -v ~/.vimrc ~/.vimrc.pre-artisan 2> /dev/null
mv -v ~/.vim ~/.vim.pre-artisan 2> /dev/null
ln -sf ~/.artisan/vim ~/.vim
brew tap MarioRicalde/vim-with-flags
brew install vim-with-flags --with-lua --with-client-server --with-override-system-vi
vim +PlugInstall +qall
