#!/bin/bash

read -p "FOR ARTISAN DEVELOPMENT ONLY, THIS WILL NUKE IT ALL! (y/n)" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  rm -rf $HOME/.tmux
  rm -rf $HOME/.tmux.conf
  rm -rf $HOME/.vim
  rm -rf $HOME/.vimrc
  rm -rf $HOME/.zshrc

  # Delete all pre-artisan archives
  find $HOME -name '*pre-artisan*' -delete

  echo "All symlinks and history removed"
fi
