#!/usr/bin/env bash
_='
┌──────────────────────────────────────────────────────────────────────────────┐
│  ╔════╗  DO NOT EDIT THIS FILE                                               │
│──╢ 🔒 ╟──────────────────────────────────────────────────────────────────────┤
│  ╚════╝  If there is an option that makes no sense, create a Pull Request.   │
╞══════════════════════════════════════════════════════════════════════════════╡
│  Docs: https://git.io/fhx1B                                 License: GPL 3.0 │
└──────────────────────────────────────────────────────────────────────────────┘
'

announce_module "Activity Monitor"
push_app "Activity Monitor"

announce "Show the main window when launching Activity Monitor"
backup_and_write 'com.apple.ActivityMonitor' 'OpenMainWindow' '-bool' 'true'

announce "Visualize CPU usage in the Activity Monitor Dock icon"
backup_and_write 'com.apple.ActivityMonitor' 'IconType' '-int' '5'

announce "Show all processes in Activity Monitor"
backup_and_write 'com.apple.ActivityMonitor' 'ShowCategory' '-int' '0'

announce "Sort Activity Monitor results by CPU usage"
backup_and_write 'com.apple.ActivityMonitor' 'SortColumn' '-string' '"CPUUsage"'
backup_and_write 'com.apple.ActivityMonitor' 'SortDirection' '-int' '0'
