#!/usr/bin/env bash
_='
┌──────────────────────────────────────────────────────────────────────────────┐
│  ╔════╗  DO NOT EDIT THIS FILE                                               │
│──╢ 🔒 ╟──────────────────────────────────────────────────────────────────────┤
│  ╚════╝  If there is an option that makes no sense, create a Pull Request.   │
╞══════════════════════════════════════════════════════════════════════════════╡
│  Docs: https://git.io/fhx1B                                 License: BSD 3-C │
└──────────────────────────────────────────────────────────────────────────────┘
'

announce_module "App Store"

announce "Enable the WebKit Developer Tools in the Mac App Store"
backup_and_write 'com.apple.appstore' 'WebKitDeveloperExtras' '-bool' 'true'

announce "Enable Debug Menu in the Mac App Store"
backup_and_write 'com.apple.appstore' 'ShowDebugMenu' '-bool' 'true'

announce "Automatically download apps purchased on other Macs"
backup_and_write 'com.apple.SoftwareUpdate' 'ConfigDataInstall' '-int' '1'

announce "Turn on app auto-update"
backup_and_write 'com.apple.commerce' 'AutoUpdate' '-bool' 'true'

