#!/usr/bin/env bash
_='
┌──────────────────────────────────────────────────────────────────────────────┐
│  ╔════╗  DO NOT EDIT THIS FILE                                               │
│──╢ 🔒 ╟──────────────────────────────────────────────────────────────────────┤
│  ╚════╝  If there is an option that makes no sense, create a Pull Request.   │
╞══════════════════════════════════════════════════════════════════════════════╡
│  Docs: https://git.io/fhx1B                                 License: BSD 3-C │
└──────────────────────────────────────────────────────────────────────────────┘
'

announce_module "Trackpad, mouse, keyboard, Bluetooth accessories, and input"

announce "Enable full keyboard access for all controls"
backup_and_write 'NSGlobalDomain' 'AppleKeyboardUIMode' '-int' '3'

announce "Use scroll gesture with the Ctrl (^) modifier key to zoom"
backup_and_write 'com.apple.universalaccess' 'closeViewScrollWheelToggle' '-bool' 'true'
backup_and_write 'com.apple.universalaccess' 'HIDScrollZoomModifierMask' '-int' '262144'

announce "Follow the keyboard focus while zoomed in"
backup_and_write 'com.apple.universalaccess' 'closeViewZoomFollowsFocus' '-bool' 'true'

announce "Disable press-and-hold for keys in favor of key repeat"
backup_and_write 'NSGlobalDomain' 'ApplePressAndHoldEnabled' '-bool' 'false'

announce "Set a blazingly fast keyboard repeat rate"
backup_and_write 'NSGlobalDomain' 'KeyRepeat' '-int' '1'
backup_and_write 'NSGlobalDomain' 'InitialKeyRepeat' '-int' '15'

announce "Disable auto-correct"
backup_and_write 'NSGlobalDomain' 'NSAutomaticSpellingCorrectionEnabled' '-bool' 'false'

announce "Disable smart QUOTES as they’re annoying when typing code"
backup_and_write 'NSGlobalDomain' 'NSAutomaticQuoteSubstitutionEnabled' '-bool' 'false'

announce "Disable smart DASHES as they’re annoying when typing code"
backup_and_write 'NSGlobalDomain' 'NSAutomaticDashSubstitutionEnabled' '-bool' 'false'

