#!/usr/bin/env bash
_='
┌──────────────────────────────────────────────────────────────────────────────┐
│  ╔════╗  DO NOT EDIT THIS FILE                                               │
│──╢ 🔒 ╟──────────────────────────────────────────────────────────────────────┤
│  ╚════╝  If there is an option that makes no sense, create a Pull Request.   │
╞══════════════════════════════════════════════════════════════════════════════╡
│  Docs: https://git.io/fhx1B                                 License: GPL 3.0 │
└──────────────────────────────────────────────────────────────────────────────┘
'

announce_module "Mail"
push_app "Mail"

announce "Disable send and reply animations in Mail.app"
backup_and_write 'com.apple.mail' 'DisableReplyAnimations' '-bool' 'true'
backup_and_write 'com.apple.mail' 'DisableSendAnimations' '-bool' 'true'

announce "Copy email addresses as 'foo@example.com' instead of 'Foo Bar <foo@example.com>' in Mail.app"
backup_and_write 'com.apple.mail' 'AddressesIncludeNameOnPasteboard' '-bool' 'false'

announce "Disable inline attachments (just show the icons)"
backup_and_write 'com.apple.mail' 'DisableInlineAttachmentViewing' '-bool' 'true'

announce "Disable automatic spell checking"
backup_and_write 'com.apple.mail' 'SpellCheckingBehavior' '-string' '"NoSpellCheckingEnabled"'
