#!/usr/bin/env bash
_='
┌──────────────────────────────────────────────────────────────────────────────┐
│  ╔════╗  DO NOT EDIT THIS FILE                                               │
│──╢ 🔒 ╟──────────────────────────────────────────────────────────────────────┤
│  ╚════╝  If there is an option that makes no sense, create a Pull Request.   │
╞══════════════════════════════════════════════════════════════════════════════╡
│  Docs: https://git.io/fhx1B                                 License: BSD 3-C │
└──────────────────────────────────────────────────────────────────────────────┘
'

announce_module "Safari & Webkit"
push_app "Safari"

announce "Don’t send search queries to Apple (privacy)"
backup_and_write 'com.apple.Safari' 'UniversalSearchEnabled' '-bool' 'false'
backup_and_write 'com.apple.Safari' 'SuppressSearchSuggestions' '-bool' 'true'

announce "Press Tab to highlight each item on a web page"
backup_and_write 'com.apple.Safari' 'WebKitTabToLinksPreferenceKey' '-bool' 'true'
backup_and_write 'com.apple.Safari' 'com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks' '-bool' 'true'

announce "Show the full URL in the address bar (note: this still hides the scheme)"
backup_and_write 'com.apple.Safari' 'ShowFullURLInSmartSearchField' '-bool' 'true'

announce "Set Safari’s home page to 'about:blank' for faster loading"
backup_and_write 'com.apple.Safari' 'HomePage' '-string' '"about:blank"'

announce "Prevent Safari from opening ‘safe’ files automatically after downloading"
backup_and_write 'com.apple.Safari' 'AutoOpenSafeDownloads' '-bool' 'false'

announce "Enable Safari’s debug menu"
backup_and_write 'com.apple.Safari' 'IncludeInternalDebugMenu' '-bool' 'true'

announce "Make Safari’s search banners default to Contains instead of Starts With"
backup_and_write 'com.apple.Safari' 'FindOnPageMatchesWordStartsOnly' '-bool' 'false'

announce "Enable the Develop menu and the Web Inspector in Safari"
backup_and_write 'com.apple.Safari' 'IncludeDevelopMenu' '-bool' 'true'
backup_and_write 'com.apple.Safari' 'WebKitDeveloperExtrasEnabledPreferenceKey' '-bool' 'true'
backup_and_write 'com.apple.Safari' 'com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled' '-bool' 'true'

announce "Add a context menu item for showing the Web Inspector in web views"
backup_and_write 'NSGlobalDomain' 'WebKitDeveloperExtras' '-bool' 'true'

announce "Enable continuous spellchecking"
backup_and_write 'com.apple.Safari' 'WebContinuousSpellCheckingEnabled' '-bool' 'true'

announce "Disable auto-correct"
backup_and_write 'com.apple.Safari' 'WebAutomaticSpellingCorrectionEnabled' '-bool' 'false'

announce "Disable AutoFill"
backup_and_write 'com.apple.Safari' 'AutoFillFromAddressBook' '-bool' 'false'
backup_and_write 'com.apple.Safari' 'AutoFillPasswords' '-bool' 'false'
backup_and_write 'com.apple.Safari' 'AutoFillCreditCardData' '-bool' 'false'
backup_and_write 'com.apple.Safari' 'AutoFillMiscellaneousForms' '-bool' 'false'

announce "Warn about fraudulent websites"
backup_and_write 'com.apple.Safari' 'WarnAboutFraudulentWebsites' '-bool' 'true'

announce "Block pop-up windows"
backup_and_write 'com.apple.Safari' 'WebKitJavaScriptCanOpenWindowsAutomatically' '-bool' 'false'
backup_and_write 'com.apple.Safari' 'com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptCanOpenWindowsAutomatically' '-bool' 'false'

announce "Enable “Do Not Track”"
backup_and_write 'com.apple.Safari' 'SendDoNotTrackHTTPHeader' '-bool' 'true'

announce "Update extensions automatically"
backup_and_write 'com.apple.Safari' 'InstallExtensionUpdatesAutomatically' '-bool' 'true'
