#!/usr/bin/env bash
_='
┌──────────────────────────────────────────────────────────────────────────────┐
│  ╔════╗  DO NOT EDIT THIS FILE                                               │
│──╢ 🔒 ╟──────────────────────────────────────────────────────────────────────┤
│  ╚════╝  If there is an option that makes no sense, create a Pull Request.   │
╞══════════════════════════════════════════════════════════════════════════════╡
│  Docs: https://git.io/fhx1B                                 License: BSD 3-C │
└──────────────────────────────────────────────────────────────────────────────┘
'

announce_module "TextEdit"
push_app "TextEdit"

announce "Use plain text mode for new TextEdit documents"
backup_and_write 'com.apple.TextEdit' 'RichText' '-int' '0'

announce "Open and save files as UTF-8 in TextEdit"
backup_and_write 'com.apple.TextEdit' 'PlainTextEncoding' '-int' '4'
backup_and_write 'com.apple.TextEdit' 'PlainTextEncodingForWrite' '-int' '4'

announce "Set tab width to 4 instead of the default 8"
backup_and_write 'com.apple.TextEdit' 'TabWidth' '4'
