
" ┌──────────────────────────────────────────────────────────────────────────────┐
" │  ╔════╗  DO NOT EDIT THIS FILE                                               │
" │──╢ 🔒 ╟──────────────────────────────────────────────────────────────────────┤
" │  ╚════╝  Instead, override settings in `~/.plug_personal`                    │
" ╞══════════════════════════════════════════════════════════════════════════════╡
" │  Docs: https://git.io/fhx1B                                 License: GPL 3.0 │
" └──────────────────────────────────────────────────────────────────────────────┘

" -- GENERAL CONFIGURATION -------------------------------------------------------

let g:startify_custom_header = [
\ '   ┌─────────────────────────────────────────────────────────────────────────┐',
\ '   │ ╔═════╗  ARTISAN                                            [stasrtify] │',
\ '   │─╢ VIM ╟─────────────────────────────────────────────────────────────────┤',
\ '   │ ╚═════╝  Press a number to open a specific file.                        │',
\ '   └─────────────────────────────────────────────────────────────────────────┘',
\ ]

" autocmd User Startified setlocal cursorline

let g:startify_enable_special      = 0
let g:startify_files_number        = 10
let g:startify_relative_path       = 1
let g:startify_change_to_dir       = 1
let g:startify_update_oldfiles     = 1
let g:startify_session_autoload    = 1
let g:startify_session_persistence = 1

let g:startify_skiplist = [
\ 'COMMIT_EDITMSG',
\ 'bundle/.*/doc',
\ '/data/repo/neovim/runtime/doc',
\ '/Users/mhi/local/vim/share/vim/vim74/doc',
\ ]

let g:startify_bookmarks = [
\ { 'cp': '~/.vimrc_personal' },
\ { 'bp': '~/.bodies_personal' },
\ { 'zp': '~/.zshrc_personal' },
\ { 'v': '~/.vimrc' },
\ { 'z': '~/.zshrc' },
\ ]


autocmd VimEnter,Colorscheme * :hi  StartifyHeader  ctermfg=3
autocmd VimEnter,Colorscheme * :hi  StartifyFooter  ctermfg=3
autocmd VimEnter,Colorscheme * :hi  StartifySection ctermfg=3

autocmd VimEnter,Colorscheme * :hi  StartifyBracket ctermfg=0
autocmd VimEnter,Colorscheme * :hi  StartifyNumber  ctermfg=2

autocmd VimEnter,Colorscheme * :hi  StartifyPath    ctermfg=4
autocmd VimEnter,Colorscheme * :hi  StartifySlash   ctermfg=7
autocmd VimEnter,Colorscheme * :hi  StartifyFile    ctermfg=7

autocmd VimEnter,Colorscheme * :hi  StartifySpecial ctermfg=1
