#!/bin/bash
source "lib/support.sh"

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `osxprep.sh` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

clear_backup true

for file in includes/recoverable/*; do
  source $file
done

#restore true

# Kill affected applications
#
# for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
#     "Dock" "Finder" "Google Chrome" "Google Chrome Canary" "Mail" "Messages" \
#     "Opera" "Safari" "SizeUp" "Spectacle" "SystemUIServer" \
#     "Transmission" "Twitter" "iCal"; do
#     killall "${app}" > /dev/null 2>&1
# done
