#!/usr/bin/env bash
_='
┌──────────────────────────────────────────────────────────────────────────────┐
│  ╔════╗  DO NOT EDIT THIS FILE                                               │
│──╢ 🔒 ╟──────────────────────────────────────────────────────────────────────┤
│  ╚════╝  If there is an option that makes no sense, create a Pull Request.   │
╞══════════════════════════════════════════════════════════════════════════════╡
│  Docs: https://git.io/fhx1B                                 License: BSD 3-C │
└──────────────────────────────────────────────────────────────────────────────┘
'

announce_module "SSD-specific tweaks"

announce "Disable hibernation (speeds up entering sleep mode)"
sudo pmset -a hibernatemode 0

announce "Remove the sleep image file to save disk space"
sudo rm -f /private/var/vm/sleepimage

announce "Create a zero-byte file instead"
sudo touch /private/var/vm/sleepimage

announce "…and make sure it can’t be rewritten"
sudo chflags uchg /private/var/vm/sleepimage
