_='
┌──────────────────────────────────────────────────────────────────────────────┐
│  ╔════╗  DO NOT EDIT THIS FILE                                               │
│──╢ 🔒 ╟──────────────────────────────────────────────────────────────────────┤
│  ╚════╝  Instead, override settings in `~/.zshrc_personal`                   │
╞══════════════════════════════════════════════════════════════════════════════╡ 
│  Docs: https://git.io/fhx1B                                 License: GPL 3.0 │ 
└──────────────────────────────────────────────────────────────────────────────┘
'
GEOMETRY_GIT_COLOR_BRANCH=8
GEOMETRY_GIT_SYMBOL_CLEAN=""
GEOMETRY_GIT_SYMBOL_DIRTY="ﯟ"
GEOMETRY_STATUS_SYMBOL=$'\ufb28 '
GEOMETRY_STATUS_SYMBOL_ERROR=$'\ufb28 '
GEOMETRY_STATUS_SYMBOL_ROOT=$'\ufacb '
GEOMETRY_STATUS_SYMBOL_ROOT_ERROR=$'\ufacb '
