_='
┌──────────────────────────────────────────────────────────────────────────────┐
│  ╔════╗  DO NOT EDIT THIS FILE                                               │
│──╢ 🔒 ╟──────────────────────────────────────────────────────────────────────┤
│  ╚════╝  Instead, override settings in `~/.zshrc_personal`                   │
╞══════════════════════════════════════════════════════════════════════════════╡ 
│  Docs: https://git.io/fhx1B                                 License: BSD 3-C │ 
└──────────────────────────────────────────────────────────────────────────────┘
'
GEOMETRY_GIT_COLOR_BRANCH=8
GEOMETRY_GIT_SYMBOL_CLEAN=""
GEOMETRY_GIT_SYMBOL_DIRTY="ﯟ"
GEOMETRY_STATUS_SYMBOL=$'\ufb28 '
GEOMETRY_STATUS_SYMBOL_ERROR=$'\ufb28 '
GEOMETRY_STATUS_SYMBOL_ROOT=$'\ufacb '
GEOMETRY_STATUS_SYMBOL_ROOT_ERROR=$'\ufacb '
GEOMETRY_STATUS_SYMBOL_COLOR_HASH="TRUE"
GEOMETRY_STATUS_SYMBOL_COLOR_HASH_COLORS=(3 150 218 231)
# 3 - yellow
# 150 - green
# 218 - pink
# 231 - white
